### ISSUE TITLE
can't install - error powershell

### ISSUE THREAD

**Issue by Makezu90** [mehraanakbarii/Croak#1]
![powershell_SnaBwIIPk9](https://github.com/mehraanakbarii/Croak/assets/89158176/ba5df81a-7274-44ee-ae28-e44658e28f35)

and it is already unzipped.

**Comment by mehraanakbarii** [comment]
Replace ExtractedZipPath with path of your extraction path :

![Desktop Screenshot 2023 05 17 - 00 11 01 61](https://github.com/mehraanakbarii/Croak/assets/120687618/36d01282-4002-4f86-ab37-38989b8a9b5a)
